[package]
name = "sqlx_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.0", features = ["full"]}
sqlx ={ version = "0.6", features = ["postgres","runtime-tokio-rustls","bigdecimal"]}
bigdecimal = "0.4"
dotenv = "0.15.0"
